name: ChrisPrender
favicon: null
layout_spectrum: 0.6280668913386762
typography_spectrum: 0.5912582578603178
title: 'Chris Prendergast - Marketer & Speaker'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.041759439278393984
  lightness: 0.02693046350032091
  saturation: 0.8569294896442443
  rhythmicContrast: 0.4762281351722777
purpose: []
